const data=[
    {
        image:'https://e1.pxfuel.com/desktop-wallpaper/149/450/desktop-wallpaper-instagram-highlight-covers-in-2020-black-instagram.jpg',
        name:'Me',
    },
    {
        image:'https://e1.pxfuel.com/desktop-wallpaper/149/450/desktop-wallpaper-instagram-highlight-covers-in-2020-black-instagram.jpg',
        name:'Me',
    },
    {
        image:'https://e1.pxfuel.com/desktop-wallpaper/149/450/desktop-wallpaper-instagram-highlight-covers-in-2020-black-instagram.jpg',
        name:'Me',
    },
    {
        image:'https://e1.pxfuel.com/desktop-wallpaper/149/450/desktop-wallpaper-instagram-highlight-covers-in-2020-black-instagram.jpg',
        name:'Me',
    },
    {
        image:'https://e1.pxfuel.com/desktop-wallpaper/149/450/desktop-wallpaper-instagram-highlight-covers-in-2020-black-instagram.jpg',
        name:'Me',
    },
]